FROM php:5.4.45-apache
LABEL MAINTAINER="ningpeng@ibmsp.com.cn"
ENV TZ=Asia/Shanghai
COPY sources.list /etc/apt/sources.list
COPY WWW /var/www/html
COPY php.ini /usr/local/etc/php/
COPY ZendGuardLoader.so /usr/src/php/libs/

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libssl-dev \
        libgmp-dev \
        libmcrypt-dev \
        libbz2-dev \
    && docker-php-ext-install iconv \
    && ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/include/gmp.h \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd mcrypt mysqli pdo pdo_mysql mysql bz2 ftp calendar exif gettext gmp shmop sockets zip\
    && echo "清理" \
    && apt-get purge -y --auto-remove \
        -o APT::AutoRemove::RecommendsImportant=false \
        -o APT::AutoRemove::SuggestsImportant=false \
        $buildDeps \
    && rm -rf /var/cache/apt/* \
    && rm -rf /var/lib/apt/lists/*
