#!/bin/bash
#

cp /etc/filebeat/filebeat.yml{,.bak}


cat<<'EOF'>/etc/filebeat/filebeat.yml
filebeat.inputs:
- type: log
  paths:
    - /var/log/tomcat/catalina.out
  # tags: ["tomcat"]
  fields:
    app: www
    type: tomcat-catalina
  fields_under_root: true
  multiline:
    pattern: '^\['
    negate: true
    match: after

output.redis:
  hosts: ["192.168.100.13"]
  password: "123456"
  key: "filebeat"
  db: 0
  datatype: list
EOF
